-- upgrade --
CREATE TABLE IF NOT EXISTS "roles" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(25) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP
);;
ALTER TABLE "user" RENAME TO "users";
ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD "is_actif" INT NOT NULL  DEFAULT 1;
ALTER TABLE "users" ADD "email_confirmed_at" TIMESTAMP;
ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE "user_roles" ("users_id" BIGINT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,"role_id" BIGINT NOT NULL REFERENCES "roles" ("id") ON DELETE CASCADE);
-- downgrade --
DROP TABLE IF EXISTS "user_roles";
ALTER TABLE "users" RENAME TO "user";
ALTER TABLE "users" DROP COLUMN "updated_at";
ALTER TABLE "users" DROP COLUMN "is_actif";
ALTER TABLE "users" DROP COLUMN "email_confirmed_at";
ALTER TABLE "users" DROP COLUMN "created_at";
DROP TABLE IF EXISTS "roles";
